[webapps]
15.206.212.192 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/homw-practise.pem

[db]
13.235.48.74 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/homw-practise.pem
